CREATE TABLE IF NOT EXISTS `tmc_welcomer_access` (
  `discord` VARCHAR(32) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `badge` VARCHAR(64) NOT NULL,
  `image` TEXT DEFAULT NULL,
  `sound` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`discord`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
